import type { Metadata } from 'next'

import localFont from 'next/font/local'
import { Toaster } from 'react-hot-toast'

import ReactQueryProviders from '@/providers/ReactQueryProvider.tsx'

import '@/app/globals.css'

const pretendard = localFont({
  src: '../static/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="kr" className={`${pretendard.variable} font-pretendard`}>
      <body>
        <ReactQueryProviders>
          <div>
            <div>{children}</div>
            <Toaster />
          </div>
          <div id="portal" />
        </ReactQueryProviders>
      </body>
    </html>
  )
}
